## Numpy & Arrays and Vectors

NumPy package contains multi-dimensional arrays, various math. operations as well as lin. algebra

In [1]:
import numpy as np

Arrays can be created with help of 'array' function

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
np.zeros((2, 3))
#np.ones((3,3))
#np.empty((2, 3, 2))
#np.arange(10)

array([[0., 0., 0.],
       [0., 0., 0.]])

Various arithmetic operations are possible. 
(Operation between equal-sized arrays are elementwise. )

In [7]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
#arr * arr
#arr - arr
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

There are multiple ways to select the elements or subsets.

In [9]:
arr0 = np.arange(15)
arr0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Do not forget indexing from the zero from the left side. 

Note that slices are 'the views' referencing to original values, and thus can be rewritten!

In [10]:
slice = arr0[0:3]
slice[1] = 12345
arr0

array([    0, 12345,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14])

In [11]:
sliceC = arr0[0:3].copy()
sliceC[1] = 6789
arr0

array([    0, 12345,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14])

In [12]:
sliceD = arr0[arr0 <5]
sliceD

array([0, 2, 3, 4])

## Pandas

Pandas contains data structures and manipulating tools to clean as well as analyse tabular and heterogenous data, having two main structures: Series and DataFrames.

In [21]:
import pandas as pd

<b>Series</b> is one dimensional array of values with labels called 'index'.
(One could also create the series from dictionary (having indices as the keys)).

In [15]:
ts = pd.Series([4, 7, -5, 3, 2, 2], index=["2018", "2019", "2020", "2021","2022", "2023"])
ts

2018    4
2019    7
2020   -5
2021    3
2022    2
2023    2
dtype: int64

In [16]:
print("Indices of ts:",ts.index)
print("Values of ts",ts.values)
print("Values of ts in 2023 is:",ts["2023"])

Indices of ts: Index(['2018', '2019', '2020', '2021', '2022', '2023'], dtype='object')
Values of ts [ 4  7 -5  3  2  2]
Values of ts in 2023 is: 2


In [17]:
ts1 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
ts1

d    4
b    7
a   -5
c    3
dtype: int64

In [18]:
ts0 = [float("NaN"), float("nan"), None]
ts2 = pd.Series(ts0)
print(ts2)
pd.isnull(ts2)

0   NaN
1   NaN
2   NaN
dtype: float64


0    True
1    True
2    True
dtype: bool

## Dataframes

<b>Dataframes</b> represents a (rectagular) table of data, in which every column can be a different type, having a row and a column index.


One way of creating a dataframe manually is via dictionary of equaly-lengthed lists.


In [22]:
data = {"state": ["Berlin", "Berlin", "Berlin", "Hamburg", "Hamburg", "Hamburg"],
        "year": [2020, 2021, 2022, 2021, 2022, 2023],
        "pop": [3.5, 3.7, 3.6, 1.4, 1.6, 1.6]}
df = pd.DataFrame(data)
df.head()

state  year  pop
0   Berlin  2020  3.5
1   Berlin  2021  3.7
2   Berlin  2022  3.6
3  Hamburg  2021  1.4
4  Hamburg  2022  1.6

In [23]:
#df["year"]
df.year
df.loc[1]

state    Berlin
year       2021
pop         3.7
Name: 1, dtype: object

If the nested dictionary is passed to dataframe, the outer keys are interpreted as the columns and the inner keys as the indices.

In [24]:
data2 = {"Hamburg": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Berlin": {2001: 3.4, 2002: 3.9}}
df2 = pd.DataFrame(data2)
df2
df2.index.name = "year"
df2.columns.name = "state"
df2
# df.T
# pd.DataFrame(data2, index=[2001, 2002, 2003])

state  Hamburg  Berlin
year                  
2000       1.5     NaN
2001       1.7     3.4
2002       3.6     3.9

In [25]:
df3 = df2.drop('Berlin',axis=1)
df4 = df3.drop(2001)
df4

state  Hamburg
year          
2000       1.5
2002       3.6

Adding two dataframes together retur dataframe whose index and columns are the unions of original ones. Rows and columns that are not found in both original dataframes are filled as missings.

In [26]:
dfA = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
dfB = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
print(dfA)
print(dfB)
dfC1 = dfA + dfB
print(dfC1)
dfC2 = dfA.add(dfB, fill_value=0)
print(dfC2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN
            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0


Pandas' objects also have a various common stats and math summarizing methods.

In [27]:
df5 = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["A", "B"])
df5

A    B
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [28]:
#df5.sum()
df5.mean(axis='rows', skipna=True)

A    3.083333
B   -2.900000
dtype: float64

In [29]:
# conda install pandas-datareader
# import pandas_datareader.data as pdr
# !pip install yfinance
import yfinance as yf

In [34]:
DataAll = {ticker: yf.download(ticker, start='2023-01-01', end='2023-02-28') for ticker in ['AAPL', 'MSFT', 'GOOG']}

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [38]:
#DataAll

In [32]:
price = pd.DataFrame({ticker:  data['Adj Close'] for ticker, data in DataAl.items()})
volume = pd.DataFrame({ticker:  data['Volume'] for ticker, data in DataAl.items()})

In [36]:
price.head()

AAPL        MSFT        GOOG
Date                                          
2022-01-03  180.683868  330.813873  145.074493
2022-01-04  178.390701  325.141388  144.416504
2022-01-05  173.645538  312.659851  137.653503
2022-01-06  170.746780  310.189270  137.550995
2022-01-07  170.915558  310.347412  137.004501

In [40]:
returns = price.pct_change()
print(returns['MSFT'].corr(returns['GOOG']))
print(returns['MSFT'].corr(returns['AAPL']))

0.8146140794752207
0.7263152525479755
